"""initial CampusPilot domain schema

Revision ID: 49badc8f2e42
Revises:
Create Date: 2026-07-28 22:46:55.687322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49badc8f2e42'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('official_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_universities')),
    sa.UniqueConstraint('code', name=op.f('uq_universities_code'))
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], name=op.f('fk_courses_university_id_universities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses')),
    sa.UniqueConstraint('university_id', 'code', name=op.f('uq_courses_university_id'))
    )
    op.create_index(op.f('ix_courses_university_id'), 'courses', ['university_id'], unique=False)
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('award_type', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], name=op.f('fk_programs_university_id_universities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_programs')),
    sa.UniqueConstraint('university_id', 'code', name=op.f('uq_programs_university_id'))
    )
    op.create_index(op.f('ix_programs_university_id'), 'programs', ['university_id'], unique=False)
    op.create_table('course_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('handbook_year', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('credit_points', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('credit_points > 0', name=op.f('ck_course_versions_positive_credit_points')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_versions_course_id_courses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_versions')),
    sa.UniqueConstraint('course_id', 'handbook_year', name=op.f('uq_course_versions_course_id'))
    )
    op.create_index(op.f('ix_course_versions_course_id'), 'course_versions', ['course_id'], unique=False)
    op.create_table('program_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('handbook_year', sa.Integer(), nullable=False),
    sa.Column('total_credits', sa.Integer(), nullable=False),
    sa.Column('max_shared_credits', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.String(length=32), nullable=True),
    sa.Column('effective_to', sa.String(length=32), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('max_shared_credits >= 0', name=op.f('ck_program_versions_non_negative_shared_credits')),
    sa.CheckConstraint('total_credits > 0', name=op.f('ck_program_versions_positive_total_credits')),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name=op.f('fk_program_versions_program_id_programs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_program_versions')),
    sa.UniqueConstraint('program_id', 'handbook_year', name=op.f('uq_program_versions_program_id'))
    )
    op.create_index(op.f('ix_program_versions_program_id'), 'program_versions', ['program_id'], unique=False)
    op.create_table('specialisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_version_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('required_credits', sa.Integer(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('required_credits >= 0', name=op.f('ck_specialisations_non_negative_required_credits')),
    sa.ForeignKeyConstraint(['program_version_id'], ['program_versions.id'], name=op.f('fk_specialisations_program_version_id_program_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_specialisations')),
    sa.UniqueConstraint('program_version_id', 'code', name=op.f('uq_specialisations_program_version_id'))
    )
    op.create_index(op.f('ix_specialisations_program_version_id'), 'specialisations', ['program_version_id'], unique=False)
    op.create_table('course_exclusions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_version_id', sa.Integer(), nullable=False),
    sa.Column('specialisation_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('excluded_course_id', sa.Integer(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('course_id <> excluded_course_id', name=op.f('ck_course_exclusions_different_excluded_course')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_exclusions_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['excluded_course_id'], ['courses.id'], name=op.f('fk_course_exclusions_excluded_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_version_id'], ['program_versions.id'], name=op.f('fk_course_exclusions_program_version_id_program_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialisation_id'], ['specialisations.id'], name=op.f('fk_course_exclusions_specialisation_id_specialisations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_exclusions')),
    sa.UniqueConstraint('program_version_id', 'specialisation_id', 'course_id', 'excluded_course_id', name=op.f('uq_course_exclusions_program_version_id'))
    )
    op.create_index(op.f('ix_course_exclusions_course_id'), 'course_exclusions', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_exclusions_excluded_course_id'), 'course_exclusions', ['excluded_course_id'], unique=False)
    op.create_index(op.f('ix_course_exclusions_program_version_id'), 'course_exclusions', ['program_version_id'], unique=False)
    op.create_index(op.f('ix_course_exclusions_specialisation_id'), 'course_exclusions', ['specialisation_id'], unique=False)
    op.create_table('prerequisite_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_version_id', sa.Integer(), nullable=False),
    sa.Column('specialisation_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('group_index', sa.Integer(), nullable=False),
    sa.Column('minimum_satisfied', sa.Integer(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('minimum_satisfied > 0', name=op.f('ck_prerequisite_groups_positive_minimum_satisfied')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_prerequisite_groups_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_version_id'], ['program_versions.id'], name=op.f('fk_prerequisite_groups_program_version_id_program_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialisation_id'], ['specialisations.id'], name=op.f('fk_prerequisite_groups_specialisation_id_specialisations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prerequisite_groups')),
    sa.UniqueConstraint('program_version_id', 'specialisation_id', 'course_id', 'group_index', name=op.f('uq_prerequisite_groups_program_version_id'))
    )
    op.create_index(op.f('ix_prerequisite_groups_course_id'), 'prerequisite_groups', ['course_id'], unique=False)
    op.create_index(op.f('ix_prerequisite_groups_program_version_id'), 'prerequisite_groups', ['program_version_id'], unique=False)
    op.create_index(op.f('ix_prerequisite_groups_specialisation_id'), 'prerequisite_groups', ['specialisation_id'], unique=False)
    op.create_table('requirement_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_version_id', sa.Integer(), nullable=False),
    sa.Column('specialisation_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.Enum('PROGRAM', 'SPECIALISATION', name='requirementscope', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('group_type', sa.Enum('CORE', 'ELECTIVE', 'CAPSTONE', name='requirementgrouptype', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('min_credits', sa.Integer(), nullable=False),
    sa.Column('max_credits', sa.Integer(), nullable=True),
    sa.Column('allow_shared_credit', sa.Boolean(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('max_credits IS NULL OR max_credits >= min_credits', name=op.f('ck_requirement_groups_valid_credit_range')),
    sa.CheckConstraint('min_credits >= 0', name=op.f('ck_requirement_groups_non_negative_min_credits')),
    sa.ForeignKeyConstraint(['program_version_id'], ['program_versions.id'], name=op.f('fk_requirement_groups_program_version_id_program_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialisation_id'], ['specialisations.id'], name=op.f('fk_requirement_groups_specialisation_id_specialisations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirement_groups')),
    sa.UniqueConstraint('program_version_id', 'specialisation_id', 'code', name=op.f('uq_requirement_groups_program_version_id'))
    )
    op.create_index(op.f('ix_requirement_groups_program_version_id'), 'requirement_groups', ['program_version_id'], unique=False)
    op.create_index(op.f('ix_requirement_groups_specialisation_id'), 'requirement_groups', ['specialisation_id'], unique=False)
    op.create_index('ix_requirement_groups_version_scope', 'requirement_groups', ['program_version_id', 'specialisation_id', 'scope'], unique=False)
    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_ref', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('program_version_id', sa.Integer(), nullable=False),
    sa.Column('specialisation_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['program_version_id'], ['program_versions.id'], name=op.f('fk_student_profiles_program_version_id_program_versions')),
    sa.ForeignKeyConstraint(['specialisation_id'], ['specialisations.id'], name=op.f('fk_student_profiles_specialisation_id_specialisations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_profiles')),
    sa.UniqueConstraint('external_ref', name=op.f('uq_student_profiles_external_ref'))
    )
    op.create_index(op.f('ix_student_profiles_program_version_id'), 'student_profiles', ['program_version_id'], unique=False)
    op.create_index(op.f('ix_student_profiles_specialisation_id'), 'student_profiles', ['specialisation_id'], unique=False)
    op.create_table('prerequisite_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_group_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_course_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prerequisite_course_id'], ['courses.id'], name=op.f('fk_prerequisite_options_prerequisite_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_group_id'], ['prerequisite_groups.id'], name=op.f('fk_prerequisite_options_prerequisite_group_id_prerequisite_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prerequisite_options')),
    sa.UniqueConstraint('prerequisite_group_id', 'prerequisite_course_id', name=op.f('uq_prerequisite_options_prerequisite_group_id'))
    )
    op.create_index(op.f('ix_prerequisite_options_prerequisite_course_id'), 'prerequisite_options', ['prerequisite_course_id'], unique=False)
    op.create_index(op.f('ix_prerequisite_options_prerequisite_group_id'), 'prerequisite_options', ['prerequisite_group_id'], unique=False)
    op.create_table('requirement_group_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_group_id', sa.Integer(), nullable=False),
    sa.Column('course_version_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('PROGRAM_CORE', 'SPECIALISATION_CORE', 'PRESCRIBED_ELECTIVE', 'GENERAL_ELECTIVE', 'CAPSTONE', 'NOT_ELIGIBLE', name='courserole', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_version_id'], ['course_versions.id'], name=op.f('fk_requirement_group_courses_course_version_id_course_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_group_id'], ['requirement_groups.id'], name=op.f('fk_requirement_group_courses_requirement_group_id_requirement_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirement_group_courses')),
    sa.UniqueConstraint('requirement_group_id', 'course_version_id', name=op.f('uq_requirement_group_courses_requirement_group_id'))
    )
    op.create_index(op.f('ix_requirement_group_courses_course_version_id'), 'requirement_group_courses', ['course_version_id'], unique=False)
    op.create_index(op.f('ix_requirement_group_courses_requirement_group_id'), 'requirement_group_courses', ['requirement_group_id'], unique=False)
    op.create_table('student_course_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'IN_PROGRESS', 'PLANNED', 'FAILED', 'EXEMPTED', 'TRANSFERRED', name='courserecordstatus', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('term_code', sa.String(length=32), nullable=True),
    sa.Column('grade', sa.String(length=16), nullable=True),
    sa.Column('credit_points_awarded', sa.Integer(), nullable=True),
    sa.Column('source_note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('attempt_number > 0', name=op.f('ck_student_course_records_positive_attempt_number')),
    sa.CheckConstraint("status NOT IN ('EXEMPTED', 'TRANSFERRED') OR credit_points_awarded IS NOT NULL", name=op.f('ck_student_course_records_explicit_adjusted_credits')),
    sa.CheckConstraint('credit_points_awarded IS NULL OR credit_points_awarded >= 0', name=op.f('ck_student_course_records_non_negative_awarded_credits')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_student_course_records_course_id_courses')),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], name=op.f('fk_student_course_records_student_id_student_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_course_records')),
    sa.UniqueConstraint('student_id', 'course_id', 'attempt_number', name=op.f('uq_student_course_records_student_id'))
    )
    op.create_index(op.f('ix_student_course_records_course_id'), 'student_course_records', ['course_id'], unique=False)
    op.create_index(op.f('ix_student_course_records_student_id'), 'student_course_records', ['student_id'], unique=False)
    op.create_index('ix_student_records_student_status', 'student_course_records', ['student_id', 'status'], unique=False)
    op.create_table('study_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='studyplanstatus', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('objective', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], name=op.f('fk_study_plans_student_id_student_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_plans'))
    )
    op.create_index(op.f('ix_study_plans_student_id'), 'study_plans', ['student_id'], unique=False)
    op.create_table('study_plan_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_plan_id', sa.Integer(), nullable=False),
    sa.Column('term_code', sa.String(length=32), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('max_credits', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('sequence_number > 0', name=op.f('ck_study_plan_terms_positive_sequence_number')),
    sa.ForeignKeyConstraint(['study_plan_id'], ['study_plans.id'], name=op.f('fk_study_plan_terms_study_plan_id_study_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_plan_terms')),
    sa.UniqueConstraint('study_plan_id', 'sequence_number', name='uq_study_plan_terms_plan_sequence'),
    sa.UniqueConstraint('study_plan_id', 'term_code', name='uq_study_plan_terms_plan_term')
    )
    op.create_index(op.f('ix_study_plan_terms_study_plan_id'), 'study_plan_terms', ['study_plan_id'], unique=False)
    op.create_table('study_plan_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_plan_term_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('preferred_role', sa.Enum('PROGRAM_CORE', 'SPECIALISATION_CORE', 'PRESCRIBED_ELECTIVE', 'GENERAL_ELECTIVE', 'CAPSTONE', 'NOT_ELIGIBLE', name='courserole', native_enum=False, create_constraint=True, length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_study_plan_courses_course_id_courses')),
    sa.ForeignKeyConstraint(['study_plan_term_id'], ['study_plan_terms.id'], name=op.f('fk_study_plan_courses_study_plan_term_id_study_plan_terms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_plan_courses')),
    sa.UniqueConstraint('study_plan_term_id', 'course_id', name=op.f('uq_study_plan_courses_study_plan_term_id'))
    )
    op.create_index(op.f('ix_study_plan_courses_course_id'), 'study_plan_courses', ['course_id'], unique=False)
    op.create_index(op.f('ix_study_plan_courses_study_plan_term_id'), 'study_plan_courses', ['study_plan_term_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_plan_courses_study_plan_term_id'), table_name='study_plan_courses')
    op.drop_index(op.f('ix_study_plan_courses_course_id'), table_name='study_plan_courses')
    op.drop_table('study_plan_courses')
    op.drop_index(op.f('ix_study_plan_terms_study_plan_id'), table_name='study_plan_terms')
    op.drop_table('study_plan_terms')
    op.drop_index(op.f('ix_study_plans_student_id'), table_name='study_plans')
    op.drop_table('study_plans')
    op.drop_index('ix_student_records_student_status', table_name='student_course_records')
    op.drop_index(op.f('ix_student_course_records_student_id'), table_name='student_course_records')
    op.drop_index(op.f('ix_student_course_records_course_id'), table_name='student_course_records')
    op.drop_table('student_course_records')
    op.drop_index(op.f('ix_requirement_group_courses_requirement_group_id'), table_name='requirement_group_courses')
    op.drop_index(op.f('ix_requirement_group_courses_course_version_id'), table_name='requirement_group_courses')
    op.drop_table('requirement_group_courses')
    op.drop_index(op.f('ix_prerequisite_options_prerequisite_group_id'), table_name='prerequisite_options')
    op.drop_index(op.f('ix_prerequisite_options_prerequisite_course_id'), table_name='prerequisite_options')
    op.drop_table('prerequisite_options')
    op.drop_index(op.f('ix_student_profiles_specialisation_id'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_program_version_id'), table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_index('ix_requirement_groups_version_scope', table_name='requirement_groups')
    op.drop_index(op.f('ix_requirement_groups_specialisation_id'), table_name='requirement_groups')
    op.drop_index(op.f('ix_requirement_groups_program_version_id'), table_name='requirement_groups')
    op.drop_table('requirement_groups')
    op.drop_index(op.f('ix_prerequisite_groups_specialisation_id'), table_name='prerequisite_groups')
    op.drop_index(op.f('ix_prerequisite_groups_program_version_id'), table_name='prerequisite_groups')
    op.drop_index(op.f('ix_prerequisite_groups_course_id'), table_name='prerequisite_groups')
    op.drop_table('prerequisite_groups')
    op.drop_index(op.f('ix_course_exclusions_specialisation_id'), table_name='course_exclusions')
    op.drop_index(op.f('ix_course_exclusions_program_version_id'), table_name='course_exclusions')
    op.drop_index(op.f('ix_course_exclusions_excluded_course_id'), table_name='course_exclusions')
    op.drop_index(op.f('ix_course_exclusions_course_id'), table_name='course_exclusions')
    op.drop_table('course_exclusions')
    op.drop_index(op.f('ix_specialisations_program_version_id'), table_name='specialisations')
    op.drop_table('specialisations')
    op.drop_index(op.f('ix_program_versions_program_id'), table_name='program_versions')
    op.drop_table('program_versions')
    op.drop_index(op.f('ix_course_versions_course_id'), table_name='course_versions')
    op.drop_table('course_versions')
    op.drop_index(op.f('ix_programs_university_id'), table_name='programs')
    op.drop_table('programs')
    op.drop_index(op.f('ix_courses_university_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_table('universities')
    # ### end Alembic commands ###
