from __future__ import annotations

from enum import Enum


class CourseRole(str, Enum):
    PROGRAM_CORE = "PROGRAM_CORE"
    SPECIALISATION_CORE = "SPECIALISATION_CORE"
    PRESCRIBED_ELECTIVE = "PRESCRIBED_ELECTIVE"
    GENERAL_ELECTIVE = "GENERAL_ELECTIVE"
    CAPSTONE = "CAPSTONE"
    NOT_ELIGIBLE = "NOT_ELIGIBLE"


class RequirementScope(str, Enum):
    PROGRAM = "PROGRAM"
    SPECIALISATION = "SPECIALISATION"


class RequirementGroupType(str, Enum):
    CORE = "CORE"
    ELECTIVE = "ELECTIVE"
    CAPSTONE = "CAPSTONE"


class CourseRecordStatus(str, Enum):
    COMPLETED = "COMPLETED"
    IN_PROGRESS = "IN_PROGRESS"
    PLANNED = "PLANNED"
    FAILED = "FAILED"
    EXEMPTED = "EXEMPTED"
    TRANSFERRED = "TRANSFERRED"


class StudyPlanStatus(str, Enum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"


class ErrorCode(str, Enum):
    OK = "OK"
    PROGRAM_VERSION_NOT_FOUND = "PROGRAM_VERSION_NOT_FOUND"
    SPECIALISATION_NOT_FOUND = "SPECIALISATION_NOT_FOUND"
    STUDENT_NOT_FOUND = "STUDENT_NOT_FOUND"
    STUDY_PLAN_NOT_FOUND = "STUDY_PLAN_NOT_FOUND"
    COURSE_NOT_FOUND = "COURSE_NOT_FOUND"
    COURSE_NOT_IN_PROGRAM = "COURSE_NOT_IN_PROGRAM"
    TOTAL_CREDITS_NOT_MET = "TOTAL_CREDITS_NOT_MET"
    PROGRAM_CORE_NOT_MET = "PROGRAM_CORE_NOT_MET"
    SPECIALISATION_CORE_NOT_MET = "SPECIALISATION_CORE_NOT_MET"
    GROUP_MIN_CREDITS_NOT_MET = "GROUP_MIN_CREDITS_NOT_MET"
    GROUP_MAX_CREDITS_EXCEEDED = "GROUP_MAX_CREDITS_EXCEEDED"
    PREREQUISITE_NOT_MET = "PREREQUISITE_NOT_MET"
    MUTUALLY_EXCLUSIVE_COURSES = "MUTUALLY_EXCLUSIVE_COURSES"
    DUPLICATE_CREDIT_COUNTING = "DUPLICATE_CREDIT_COUNTING"
    PLAN_COURSE_ALREADY_COMPLETED = "PLAN_COURSE_ALREADY_COMPLETED"
